Widgets panel
googleinterns/earthengine-community pull request #2
Opened 2020-05-19 17:39 UTC by mibrah42

## What are we adding in this PR 

This PR adds the following widgets:

- [x] `<actions-panel />`: Left Side panel that allows users to interact with the template preview. Contains tabs for different functionality (selecting templates, adding widgets, and modifying attributes).
- [x]  `<draggable-widget />`: A widget that wraps around other widgets to make them draggable.
- [x]  `<ui-label />`: A text widget that allows users to add text to their templates.
- [x]  `<tab-container />`: A widget that wraps around a set of components for each tab of the actions panel.
- [x]  `<widgets-tab />`: A widget that contains the different widgets that the user can add to their template.

## Screenshot 
![image](https://user-images.githubusercontent.com/26859947/82359673-30dc0c80-99d6-11ea-9c50-c536b6e76583.png)

2020-05-19 23:22 UTC, sufyanAbbasi requested changes
Fantastic! I mostly left trivial comments (nits) and the changes should be quick.

My apologies for not documenting the properties on the widgets very well when I made them. I think it would be a good idea to leave JSDoc comments above all properties, to get you in the habit of documenting the code as you write it!

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/actions-panel/actions-panel.ts
> + *  all template actions are taking place. This includes selecting templates,
nit: `all template actions take place.`

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/actions-panel/actions-panel.ts
> +    if (panel == null) return;
nit: Use full if blocks:
```
if (panel == null) {
 return;
}
```

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/actions-panel/test/actions-panel_test.ts
> + *  These actions include selecting templates, adding widgets, and editting different attributes.
nit: Shorten comment to: `This file tests the actions panel widget.`

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/draggable-widget/draggable-widget.ts
> + *  @fileoverview The draggable widget wraps around other widgets to make them draggable
nit: Add a period to the end (and remove around):
The draggable widget wraps other widgets to make them draggable.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/actions-panel/actions-panel.ts
> +          ${widgetsMarkup}
Use `nothing` instead, since it's more semantic:

${ selectedTab === 1 ? html`<widgets-tab></widgets-tab>` : nothing }

https://lit-html.polymer-project.org/guide/writing-templates#rendering-nothing

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/draggable-widget/draggable-widget.ts
> +        ${overlay}
Same: use `nothing`:
https://lit-html.polymer-project.org/guide/writing-templates#rendering-nothing

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/draggable-widget/test/draggable-widget_test.ts
> + *  @fileoverview This file tests the draggable-widget which wraps
nit: shorten to: `This file tests the draggable-widget.`

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/tab-container/tab-container.ts
> + *  in the actions panel
nit: period at the end.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/tab-container/test/tab-container_test.ts
> + *  @fileoverview This file tests the tab container widget which
nit: shorten here as well.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/tab-container/test/tab-container_test.ts
> +      `
Better to query select the h5 element and check its textContent, since it's less brittle to changes. Further, you may want to forego checking for the h5 element altogether since that's an implementation detail. Simply check that the textContent of the shadowDom contains the title.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/tool-bar/tool-bar.ts
> + *  @fileoverview The tool-bar widget is the header component
nit: period at the end.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-button/test/ui-button_test.ts
> + *  @fileoverview This file tests the ui-button widget which enables users to add a buttons to their templates
nit: shorten here as well.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/tab-container/tab-container.ts
> +
Add a JSDoc string comment to this property (and others):

```
/**
 * The title of the tab container.
 */
```

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-button/ui-button.ts
> +
Add JSDoc string to these properties and below.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-checkbox/test/ui-checkbox_test.ts
> + *  @fileoverview This file tests the ui-checkbox widget
nit:`This file tests the ui-checkbox widget.`

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-checkbox/ui-checkbox.ts
> + *  @fileoverview The ui-checkbox widget lets users add a checkbox component to their templates
nit: period at the end.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-checkbox/ui-checkbox.ts
> +
Add JSDoc comments to these properties.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-label/test/ui-label_test.ts
> + *  @fileoverview This file tests the ui-label widget
nit: shorten here as well.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-label/ui-label.ts
> + *  text to their templates
nit: period.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-label/ui-label.ts
> +  @property({ type: String }) value = '';
Same here: JSDoc comments.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-select/test/ui-select_test.ts
> + *  @fileoverview
nit: fill this in.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-select/ui-select.ts
> +
JSDoc comments here.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/ui-textbox/test/ui-textbox_test.ts
> + *  @fileoverview This file tests the ui-textbox widget
nit: same, shorten.

2020-05-19 23:22 UTC, sufyanAbbasi commented on app-creator/src/widgets/widgets-tab/widgets-tab.ts
> +          <!-- courtsey of http://khaledipsum.com/ -->
nit: courtesy also, 😭

2020-05-20 16:45 UTC, joannalcy commented on app-creator/src/widgets/ui-textbox/ui-textbox.ts
> +  getAlwaysFloatLabel() {
This might not work for the textbox in code editor?

2020-05-20 16:45 UTC, joannalcy commented on app-creator/src/widgets/ui-label/ui-label.ts
> +      class=${contentClass}
It looks like type would be either 'paragraph' or 'title', so can we replace contentClass with this.type?

2020-05-20 16:45 UTC, joannalcy commented on app-creator/src/widgets/ui-button/ui-button.ts
> +    return html` <paper-button
Nit: move this tag to the next line?

2020-05-20 16:45 UTC, joannalcy commented on app-creator/src/widgets/actions-panel/actions-panel.ts
> +  togglePanel({ target }: { target: EventTarget }) {
Since it's a big function, could you add docstring to explain what it does?

2020-05-20 17:10 UTC, joannalcy commented on app-creator/src/widgets/ui-select/ui-select.ts
> +    return html` <paper-dropdown-menu
Nit: Change line here?

2020-05-20 17:10 UTC, joannalcy commented on app-creator/src/widgets/ui-label/ui-label.ts
> +    return html` <iron-label class=${type} style=${styleMap(this.styles)}>
Nit: Change line here?

2020-05-20 17:12 UTC, joannalcy approved these changes

2020-05-20 17:38 UTC, merged