Code export
googleinterns/earthengine-community pull request #27
Opened 2020-08-16 08:10 UTC by mibrah42

## What are we adding in this PR

This PR adds a toggle in the exports dialog for switching between an example code snippet and the raw JSON string. The code snippet is useful for creating single app instances, while the JSON string is more useful for creating responsive and multi-selector apps. 

**Code snippet**
<img src="https://user-images.githubusercontent.com/26859947/90329852-09b1be80-df76-11ea-88c8-8d7138451b86.png" width="600px">

**JSON**
<img src="https://user-images.githubusercontent.com/26859947/90329841-fa327580-df75-11ea-98f9-aa45cd732903.png" width="600px">

2020-08-18 06:27 UTC, sufyanAbbasi requested changes
Nice work on cleaning up and accentuating these features; I see that you encountered some interesting coding challenges when writing this. Unfortunately, I believe there are some challenges that haven't been fully solved yet!

2020-08-18 06:27 UTC, sufyanAbbasi commented on app-creator/client/src/client/fetch-templates.ts
> +            "version": "1.0",
Let's use https://semver.org notation for versioning, starting with 0.0.0 (our client libraries are at version 0.1.230 right now). I also believe that we should implement versioning at a global level instead of on a per template level, probably declared in `constants.ts`. Maybe there's a central place we can inject it, like at export time?

2020-08-18 06:27 UTC, sufyanAbbasi commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +    `;
Let's declare this string in `constants.ts`.

2020-08-18 06:27 UTC, sufyanAbbasi commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +    if (this.selectedTab === 0) {
This is better expressed as an enum (also below on line 310):
```ts
enum Tab {
  CODE = 0,
  JSON = 1,
}
...
if (this.selectedTab === Tab.CODE) {
...
```

2020-08-18 06:27 UTC, sufyanAbbasi commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +   * Correctly formats dataTable into JSON string.
Include a short example string representing a data table.

2020-08-18 06:27 UTC, sufyanAbbasi commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +  private normalizeDataTable(dataTable: string) {
I started to comment on improvements to your regexes until I realized how difficult the problem actually is. Your best best is to use this third party library: https://github.com/json5/json5, which has already solved this problem, so you can simply call: `JSON5.parse(dataTable)` before stringifying it.

See this stack overflow: https://stackoverflow.com/a/49188147

```
Knowledge is writing a regular expression that produces valid JSON.
Wisdom is using a reputable library that does it for you.
```

2020-08-18 06:27 UTC, sufyanAbbasi commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +  private normalizeTemplate(template: AppCreatorStore['template']) {
Move this and the following methods to `utils/helpers.ts`.

2020-08-18 06:27 UTC, sufyanAbbasi commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +          </paper-tab>
You should be able to iterate on the key/values of the proposed enum above to produce these `paper-tab` elements dynamically.

2020-08-18 06:27 UTC, sufyanAbbasi commented on app-creator/data/data.go
> +	Version float32 `json:"version"`
Use a string instead to handle the double dots in the version.
Side note: how do we keep the templates stored in the datastore in sync with the ones served as a backup? We can chat about this offline.

2020-08-18 23:55 UTC, mibrah42 commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +    `;
We are injecting the template inside of the string. I'll add the method to helper.ts instead. Alternatively we can have a constant with some symbol (i.e. '#') and we split the string on it and join with the template.

2020-08-19 00:56 UTC, mibrah42 commented on app-creator/client/src/utils/helpers.ts
> + * Get sample code snippet for creating an app on the code editor.
We need this to be a function rather than a constant since it injects the template inside.

2020-08-19 01:11 UTC, sufyanAbbasi commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +    `;
Ah, I totally missed that. `helper.ts` is fine!

2020-08-19 04:16 UTC, sufyanAbbasi approved these changes
One small comment and it will be good to go!

2020-08-19 04:16 UTC, sufyanAbbasi commented on app-creator/client/src/widgets/tool-bar/tool-bar.ts
> +    if (this.selectedTab === 0) {
ExportTab enum here too.

2020-08-25 05:44 UTC, sufyanAbbasi approved these changes
Thank you!

2020-08-25 07:56 UTC, merged